const base64String = 'eyJwZW9wbGUiOlt7ImlkIjoiMTc1MjU0NTA2MzY1MyIsIm5hbWUiOiLsp4Drr7wifSx7ImlkIjoiMTc1MjU0NTA2NTEwNSIsIm5hbWUiOiLqt5zruYgifSx7ImlkIjoiMTc1MjU0NTA2NzE4MCIsIm5hbWUiOiLslYTsmIEifSx7ImlkIjoiMTc1MjU0NTA3MTM1MyIsIm5hbWUiOiLsoJXshK0ifSx7ImlkIjoiMTc1MjU0NTA3OTU1NSIsIm5hbWUiOiLsmIjsiqwifSx7ImlkIjoiMTc1MjU0NTA5NTQ5NCIsIm5hbWUiOiLspIDqsr0ifSx7ImlkIjoiMTc1MjU0NTA5OTQ3OCIsIm5hbWUiOiLsnKTsoJUifSx7ImlkIjoiMTc1MjU0NTEwNzQ2NCIsIm5hbWUiOiLsp4DtmIQifSx7ImlkIjoiMTc1MjU0NTExMDg0MyIsIm5hbWUiOiLsmrDtmJUifV0sImV4cGVuc2VzIjpbeyJpZCI6IjE3NTI1NDUxNDI2NTAiLCJuYW1lIjoi66eJ6rWt7IiYIC0g7YWM7J2067iUIDEiLCJhbW91bnQiOjk2MDAwLCJwYWlkQnkiOiIxNzUyNTQ1MDY3MTgwIiwic3BsaXRBbW9uZyI6WyIxNzUyNTQ1MDY1MTA1IiwiMTc1MjU0NTA2NzE4MCIsIjE3NTI1NDUwNzk1NTUiLCIxNzUyNTQ1MDk5NDc4IiwiMTc1MjU0NTEwNzQ2NCJdfSx7ImlkIjoiMTc1MjU0NTIyMDgzMyIsIm5hbWUiOiLrp4nqta3siJggLSDthYzsnbTruJQyIiwiYW1vdW50Ijo5ODAwMCwicGFpZEJ5IjoiMTc1MjU0NTA2MzY1MyIsInNwbGl0QW1vbmciOlsiMTc1MjU0NTA2MzY1MyIsIjE3NTI1NDUwNzEzNTMiLCIxNzUyNTQ1MDk1NDk0IiwiMTc1MjU0NTExMDg0MyJdfSx7ImlkIjoiMTc1MjU0NTMxMjk0NyIsIm5hbWUiOiLrgq3rp4zsp5zsnqUiLCJhbW91bnQiOjc1MjAwLCJwYWlkQnkiOiIxNzUyNTQ1MDY1MTA1Iiwic3BsaXRBbW9uZyI6WyIxNzUyNTQ1MDY1MTA1IiwiMTc1MjU0NTA3MTM1MyIsIjE3NTI1NDUwNzk1NTUiLCIxNzUyNTQ1MDk1NDk0Il19LHsiaWQiOiIxNzUyNTQ1Mzc2NjQ3IiwibmFtZSI6IuyVvOqwhCDtjrjsnZjsoJAiLCJhbW91bnQiOjQ5NTAwLCJwYWlkQnkiOiIxNzUyNTQ1MDY1MTA1Iiwic3BsaXRBbW9uZyI6WyIxNzUyNTQ1MDYzNjUzIiwiMTc1MjU0NTA2NTEwNSIsIjE3NTI1NDUwNzEzNTMiLCIxNzUyNTQ1MDc5NTU1IiwiMTc1MjU0NTA5NTQ5NCIsIjE3NTI1NDUwOTk0NzgiLCIxNzUyNTQ1MTEwODQzIl19LHsiaWQiOiIxNzUyNTQ1NDM3NDA4IiwibmFtZSI6Iuq3nOu5iCDsnKDrpZjruYQiLCJhbW91bnQiOjMzMTAwLCJwYWlkQnkiOiIxNzUyNTQ1MDY1MTA1Iiwic3BsaXRBbW9uZyI6WyIxNzUyNTQ1MDY1MTA1IiwiMTc1MjU0NTA3MTM1MyIsIjE3NTI1NDUwNzk1NTUiLCIxNzUyNTQ1MDk1NDk0Il19LHsiaWQiOiIxNzUyNTQ1NTA5MDcxIiwibmFtZSI6IuyImeyGjC0g7JW87IudIiwiYW1vdW50IjoxMzUzMDAsInBhaWRCeSI6IjE3NTI1NDUwOTU0OTQiLCJzcGxpdEFtb25nIjpbIjE3NTI1NDUwNjM2NTMiLCIxNzUyNTQ1MDY1MTA1IiwiMTc1MjU0NTA3MTM1MyIsIjE3NTI1NDUwNzk1NTUiLCIxNzUyNTQ1MDk1NDk0IiwiMTc1MjU0NTA5OTQ3OCIsIjE3NTI1NDUxMTA4NDMiXX0seyJpZCI6IjE3NTI1NDU1NTgzNTciLCJuYW1lIjoi7KCA7IiY7KeAIOyYpOumrOuwsCIsImFtb3VudCI6NDQwMDAsInBhaWRCeSI6IjE3NTI1NDUwNjM2NTMiLCJzcGxaXRBbW9uZyI6WyIxNzUyNTQ1MDYzNjUzIiwiMTc1MjU0NTA2NTEwNSIsIjE3NTI1NDUwNzEzNTMiLCIxNzUyNTQ1MDc5NTU1IiwiMTc1MjU0NTA5NTQ5NCIsIjE3NTI1NDUwOTk0NzgiXX0seyJpZCI6IjE3NTI1NDU2NTU2MzEiLCJuYW1lIjoi7Iit7IaMIC0g7J247JuQIOy2lOqwgCDsnbTttogiLCJhbW91bnQiOjMwMDAwLCJwYWlkQnkiOiIxNzUyNTQ1MDYzNjUzIiwic3BsaXRBbW9uZyI6WyIxNzUyNTQ1MDYzNjUzIiwiMTc1MjU0NTA2NTEwNSIsIjE3NTI1NDUwNzEzNTMiLCIxNzUyNTQ1MDc5NTU1IiwiMTc1MjU0NTA5NTQ5NCIsIjE3NTI1NDUwOTk0NzgiLCIxNzUyNTQ1MTEwODQzIl19LHsiaWQiOiIxNzUyNTQ1OTMyMjUyIiwibmFtZSI6Iuuuk+uurOygnOyepSAtIOyngOuvvCIsImFtb3VudCI6MjEzMDAsInBhaWRCeSI6IjE3NTI1NDUwNjM2NTMiLCJzcGxpdEFtb25nIjpbIjE3NTI1NDUwNjM2NTMiLCIxNzUyNTQ1MDk5NDc4IiwiMTc1MjU0NTExMDg0MyJdfV0sImdyb3VwTmFtZSI6IuqwleybkOybkOygleydgCAifQ';

// Fix the corrupted base64 string
const fixedBase64 = base64String.replace('splZXRBbW9uZyI6', 'splitAmong":');

try {
  const decodedString = decodeURIComponent(escape(atob(fixedBase64)));
  const data = JSON.parse(decodedString);
  
  console.log('그룹 이름:', data.groupName);
  console.log('\n참가자 (' + data.people.length + '명):');
  data.people.forEach(p => console.log(' -', p.name));
  
  console.log('\n비용 내역:');
  let totalAmount = 0;
  data.expenses.forEach(expense => {
    const payer = data.people.find(p => p.id === expense.paidBy);
    const payerName = payer ? payer.name : 'Unknown';
    console.log(` - ${expense.name}: ₩${expense.amount.toLocaleString()} (결제: ${payerName}, 분할: ${expense.splitAmong.length}명)`);
    totalAmount += expense.amount;
  });
  
  console.log('\n총 비용: ₩' + totalAmount.toLocaleString());
} catch (error) {
  console.error('Error decoding:', error);
}